[Log]
Level = 'warn'

[WebServer]
AllowOrigins = '*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '5611'
LogBackfillBatchSize = 500

[[EVM.Nodes]]
Name = 'opBNB Testnet'
WSURL = 'wss://opbnb-testnet.g.alchemy.com/v2/ARfC3VfgsUf8q3AG2NFnQ37Zps_XgTaV'
HTTPURL = 'https://opbnb-testnet.g.alchemy.com/v2/ARfC3VfgsUf8q3AG2NFnQ37Zps_XgTaV'

[EVM.GasEstimator]
Mode = 'FixedPrice'
PriceDefault = '10000000000'
