[Log]
Level = 'info'

[WebServer]
AllowOrigins = '*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[Feature]
FeedsManager = true
LogPoller = false
UICSAKeys = false
CCIP = false
MultiFeedsManagers = false

[[EVM]]
ChainID = '5611'
LogBackfillBatchSize = 500
LinkContractAddress = '0xDA333D5948610a7634202A9420c0c17034B6484A'

[[EVM.Nodes]]
Name = 'opbnb-testnet-1-primary'
WSURL = 'wss://opbnb-testnet.nodereal.io/ws/v1/e9a36765eb8a40b9bd12e680a1fd2bc5'
HTTPURL = 'https://opbnb-testnet-rpc.bnbchain.org'
SendOnly = false

[EVM.GasEstimator]
Mode = 'FixedPrice'
PriceDefault = '20'
PriceMax = '1000 gwei'
PriceMin = '1 wei'
LimitDefault = 500000
LimitMax = 500000
LimitMultiplier = '1'
LimitTransfer = 21000
EstimateLimit = false
BumpMin = '100 wei'
BumpPercent = 20
BumpThreshold = 3
EIP1559DynamicFees = true
FeeCapDefault = '1000000'
TipCapDefault = '1 wei'
TipCapMin = '1 wei'

[EVM.GasEstimator.BlockHistory]
BatchSize = 25
BlockHistorySize = 24
CheckInclusionBlocks = 12
CheckInclusionPercentile = 90
TransactionPercentile = 60

[EVM.GasEstimator.FeeHistory]
CacheTimeout = '10s'

[OCR]
Enabled = true
ObservationTimeout = '5s'
BlockchainTimeout = '20s'
ContractPollInterval = '1m0s'
ContractSubscribeInterval = '2m0s'
DefaultTransactionQueueDepth = 1
KeyBundleID = '3af6e79d98c2fcb39e8f7f0ca4d9501f277148dde5c79ac6e8575e7c52096e74'
SimulateTransactions = false
TransmitterAddress = '0xfEAd444FA26479855Ce93f6fd959D5368347C849'
CaptureEATelemetry = false
TraceLogging = false
ConfigLogValidation = false

[P2P]
IncomingMessageBufferSize = 10 # Default
OutgoingMessageBufferSize = 10 # Default
TraceLogging = true # Default

[P2P.V2]
Enabled = true # Default
AnnounceAddresses = ['10.5.0.9:9999']
DefaultBootstrappers = []
DeltaDial = '15s' # Default
DeltaReconcile = '1m' # Default
ListenAddresses = ['0.0.0.0:9999'] # Example
