[Log]
Level = 'info'

[WebServer]
AllowOrigins = '*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '5611'
LogBackfillBatchSize = 500

[[EVM.Nodes]]
Name = 'opBNB Testnet'
WSURL = 'wss://opbnb-testnet-rpc.publicnode.com'
HTTPURL = 'https://opbnb-testnet-rpc.publicnode.com'

#[EVM.GasEstimator]
#Mode = 'FixedPrice'
#PriceDefault = '1000000000'

[EVM.GasEstimator]
Mode = 'FixedPrice'
PriceDefault = '20'
PriceMax = '115792089237316195423570985008687907853269984665.640564039457584007913129639935 tether'
PriceMin = '1 wei'
LimitDefault = 500000
LimitMax = 500000
LimitMultiplier = '1'
LimitTransfer = 21000
EstimateLimit = false
BumpMin = '100 wei'
BumpPercent = 20
BumpThreshold = 3
EIP1559DynamicFees = true
FeeCapDefault = '1000000'
TipCapDefault = '1 wei'
TipCapMin = '1 wei'

[EVM.GasEstimator.BlockHistory]
BatchSize = 25
BlockHistorySize = 24
CheckInclusionBlocks = 12
CheckInclusionPercentile = 90
TransactionPercentile = 60

[EVM.GasEstimator.FeeHistory]
CacheTimeout = '10s'

[OCR]
Enabled = true

[P2P]
IncomingMessageBufferSize = 10 # Default
OutgoingMessageBufferSize = 10 # Default
# PeerID = '12D3KooWMoejJznyDuEk5aX6GvbjaG12UzeornPCBNzMRqdwrFJw' # Example
TraceLogging = true # Default

[P2P.V2]
Enabled = true # Default
AnnounceAddresses = ['10.5.0.12:9999']
DefaultBootstrappers = ['12D3KooWEi8nVgEuHvbL8n4Sp2BvmJUkaoi9ANyN1MURAUX2KP61@10.5.0.9:9999']
DeltaDial = '15s' # Default
DeltaReconcile = '1m' # Default
ListenAddresses = ['0.0.0.0:9999'] # Example
