[Log]
Level = 'info'

[WebServer]
AllowOrigins = '*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[Feature]
FeedsManager = true
LogPoller = false
UICSAKeys = false
CCIP = false
MultiFeedsManagers = false

[[EVM]]
ChainID = '5611'
LogBackfillBatchSize = 500
LinkContractAddress = '0xDA333D5948610a7634202A9420c0c17034B6484A'

[[EVM.Nodes]]
Name = 'opbnb-testnet-3-primary'
WSURL = 'wss://opbnb-testnet.nodereal.io/ws/v1/e9a36765eb8a40b9bd12e680a1fd2bc5'
HTTPURL = 'https://opbnb-testnet-rpc.bnbchain.org'
SendOnly = false

[EVM.GasEstimator]
Mode = 'FixedPrice'
PriceDefault = '20'
PriceMax = '1000 gwei'
PriceMin = '1 wei'
LimitDefault = 500000
LimitMax = 500000
LimitMultiplier = '1'
LimitTransfer = 21000
EstimateLimit = false
BumpMin = '100 wei'
BumpPercent = 20
BumpThreshold = 3
EIP1559DynamicFees = true
FeeCapDefault = '1000000'
TipCapDefault = '1 wei'
TipCapMin = '1 wei'

[EVM.GasEstimator.BlockHistory]
BatchSize = 25
BlockHistorySize = 24
CheckInclusionBlocks = 12
CheckInclusionPercentile = 90
TransactionPercentile = 60

[EVM.GasEstimator.FeeHistory]
CacheTimeout = '10s'

[OCR]
Enabled = true
ObservationTimeout = '5s'
BlockchainTimeout = '20s'
ContractPollInterval = '1m0s'
ContractSubscribeInterval = '2m0s'
DefaultTransactionQueueDepth = 1
KeyBundleID = 'a625c75d9539820d101ff8e4366142d1cdf1111f863ca4a44639efd0e4716a7c'
SimulateTransactions = false
TransmitterAddress = '0x03Fd5B42d6fFb1A675f4d2cd3d4fCCB9aD902F5f'
CaptureEATelemetry = false
TraceLogging = false
ConfigLogValidation = false

[P2P]
IncomingMessageBufferSize = 10 # Default
OutgoingMessageBufferSize = 10 # Default
TraceLogging = true # Default

[P2P.V2]
Enabled = true # Default
AnnounceAddresses = ['10.5.0.11:9999']
DefaultBootstrappers = ['12D3KooWQCqrvShyy9GeypXXCoK9im5hxLEiyqGuUHeLDbZbYktv@10.5.0.9:9999']
DeltaDial = '15s' # Default
DeltaReconcile = '1m' # Default
ListenAddresses = ['0.0.0.0:9999'] # Example
