[Log]
Level = 'info'

[WebServer]
AllowOrigins = '*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '5611'
LogBackfillBatchSize = 500

[[EVM.Nodes]]
Name = 'opBNB Testnet'
WSURL = 'wss://opbnb-testnet.nodereal.io/ws/v1/e9a36765eb8a40b9bd12e680a1fd2bc5'
HTTPURL = 'https://opbnb-testnet-rpc.bnbchain.org'

[EVM.GasEstimator]
Mode = 'FixedPrice'
PriceDefault = '1000000000'

[OCR]
Enabled = true

[P2P]
IncomingMessageBufferSize = 10 # Default
OutgoingMessageBufferSize = 10 # Default
# PeerID = '12D3KooWMoejJznyDuEk5aX6GvbjaG12UzeornPCBNzMRqdwrFJw' # Example
TraceLogging = true # Default

[P2P.V2]
Enabled = true # Default
AnnounceAddresses = ['10.5.0.11:9999'] # Example
DefaultBootstrappers = ['12D3KooWJxKTff9iStekSuR3EU5bxxqe9FUSVgATsyChdB3N6nuH@10.5.0.9:9999'] # Example
DeltaDial = '15s' # Default
DeltaReconcile = '1m' # Default
ListenAddresses = ['0.0.0.0:9999'] # Example
