type = "offchainreporting"
schemaVersion = 1
name = "1INCH / ETH"
externalJobID = "0a30b2fd-0186-51c6-9773-b8bbeada8764"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        alphavantage_1inch_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/alphavantage/1INCH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        alphavantage_1inch_usd_parse    [type="jsonparse" path="price"]
        alphavantage_1inch_usd_multiply [type="multiply" times=1000000000000000000]

        alphavantage_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/alphavantage/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        alphavantage_eth_usd_parse    [type="jsonparse" path="price"]
        alphavantage_eth_usd_multiply [type="multiply" times=1000000000000000000]

        alphavantage_1inch_eth_divide    [type="divide" input="$(alphavantage_1inch_usd_multiply)" divisor="$(alphavantage_eth_usd_multiply)" times=1000000000000000000]

        binance_1inch_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/1INCH/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_1inch_usdt_parse    [type="jsonparse" path="price"]
        binance_1inch_usdt_multiply [type="multiply" times=1000000000000000000]

        binance_eth_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/ETH/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_eth_usdt_parse    [type="jsonparse" path="price"]
        binance_eth_usdt_multiply [type="multiply" times=1000000000000000000]

        binance_1inch_eth_divide    [type="divide" input="$(binance_1inch_usdt_multiply)" divisor="$(binance_eth_usdt_multiply)" times=1000000000000000000]

        coinbase_1inch_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/1INCH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_1inch_usd_parse    [type="jsonparse" path="price"]
        coinbase_1inch_usd_multiply [type="multiply" times=1000000000000000000]

        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]
        coinbase_eth_usd_multiply [type="multiply" times=1000000000000000000]

        coinbase_1inch_eth_divide    [type="divide" input="$(coinbase_1inch_usd_multiply)" divisor="$(coinbase_eth_usd_multiply)" times=1000000000000000000]

        coingecko_1inch_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/1inch/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_1inch_usd_parse    [type="jsonparse" path="price"]
        coingecko_1inch_usd_multiply [type="multiply" times=1000000000000000000]

        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/ethereum/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]
        coingecko_eth_usd_multiply [type="multiply" times=1000000000000000000]

        coingecko_1inch_eth_divide    [type="divide" input="$(coingecko_1inch_usd_multiply)" divisor="$(coingecko_eth_usd_multiply)" times=1000000000000000000]

        cryptocompare_1inch_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/1INCH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_1inch_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_1inch_usd_multiply [type="multiply" times=1000000000000000000]

        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_eth_usd_multiply [type="multiply" times=1000000000000000000]

        cryptocompare_1inch_eth_divide    [type="divide" input="$(cryptocompare_1inch_usd_multiply)" divisor="$(cryptocompare_eth_usd_multiply)" times=1000000000000000000]

        kraken_1inch_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/1INCH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_1inch_usd_parse    [type="jsonparse" path="price"]
        kraken_1inch_usd_multiply [type="multiply" times=1000000000000000000]

        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]
        kraken_eth_usd_multiply [type="multiply" times=1000000000000000000]

        kraken_1inch_eth_divide    [type="divide" input="$(kraken_1inch_usd_multiply)" divisor="$(kraken_eth_usd_multiply)" times=1000000000000000000]

        okx_1inch_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/1INCH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_1inch_usd_parse    [type="jsonparse" path="price"]
        okx_1inch_usd_multiply [type="multiply" times=1000000000000000000]

        okx_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_eth_usd_parse    [type="jsonparse" path="price"]
        okx_eth_usd_multiply [type="multiply" times=1000000000000000000]

        okx_1inch_eth_divide    [type="divide" input="$(okx_1inch_usd_multiply)" divisor="$(okx_eth_usd_multiply)" times=1000000000000000000]

        median [type=median];

    alphavantage_1inch_usd -> alphavantage_1inch_usd_parse -> alphavantage_1inch_usd_multiply -> alphavantage_1inch_eth_divide
    alphavantage_eth_usd -> alphavantage_eth_usd_parse -> alphavantage_eth_usd_multiply -> alphavantage_1inch_eth_divide
    binance_1inch_usdt -> binance_1inch_usdt_parse -> binance_1inch_usdt_multiply -> binance_1inch_eth_divide
    binance_eth_usdt -> binance_eth_usdt_parse -> binance_eth_usdt_multiply -> binance_1inch_eth_divide
    coinbase_1inch_usd -> coinbase_1inch_usd_parse -> coinbase_1inch_usd_multiply -> coinbase_1inch_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_eth_usd_multiply -> coinbase_1inch_eth_divide
    coingecko_1inch_usd -> coingecko_1inch_usd_parse -> coingecko_1inch_usd_multiply -> coingecko_1inch_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_eth_usd_multiply -> coingecko_1inch_eth_divide
    cryptocompare_1inch_usd -> cryptocompare_1inch_usd_parse -> cryptocompare_1inch_usd_multiply -> cryptocompare_1inch_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_eth_usd_multiply -> cryptocompare_1inch_eth_divide
    kraken_1inch_usd -> kraken_1inch_usd_parse -> kraken_1inch_usd_multiply -> kraken_1inch_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_eth_usd_multiply -> kraken_1inch_eth_divide
    okx_1inch_usd -> okx_1inch_usd_parse -> okx_1inch_usd_multiply -> okx_1inch_eth_divide
    okx_eth_usd -> okx_eth_usd_parse -> okx_eth_usd_multiply -> okx_1inch_eth_divide
    alphavantage_1inch_eth_divide -> median;
    binance_1inch_eth_divide -> median;
    coinbase_1inch_eth_divide -> median;
    coingecko_1inch_eth_divide -> median;
    cryptocompare_1inch_eth_divide -> median;
    kraken_1inch_eth_divide -> median;
    okx_1inch_eth_divide -> median;
"""
