type = "offchainreporting"
schemaVersion = 1
name = "AAVE / ETH"
externalJobID = "e1e56bbe-5084-545f-9088-3357a9e8ba26"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        alphavantage_aave_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/alphavantage/AAVE/USD" allowUnrestrictedNetworkAccess=true retries=3]
        alphavantage_aave_usd_parse    [type="jsonparse" path="price"]
        alphavantage_aave_usd_multiply [type="multiply" times=1000000000000000000]
    
        alphavantage_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/alphavantage/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        alphavantage_eth_usd_parse    [type="jsonparse" path="price"]
        alphavantage_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        alphavantage_aave_eth_divide    [type="divide" input="$(alphavantage_aave_usd_multiply)" divisor="$(alphavantage_eth_usd_multiply)" times=1000000000000000000]
    
        binance_aave_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/AAVE/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_aave_usdt_parse    [type="jsonparse" path="price"]
        binance_aave_usdt_multiply [type="multiply" times=1000000000000000000]
    
        binance_eth_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/ETH/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_eth_usdt_parse    [type="jsonparse" path="price"]
        binance_eth_usdt_multiply [type="multiply" times=1000000000000000000]
    
        binance_aave_eth_divide    [type="divide" input="$(binance_aave_usdt_multiply)" divisor="$(binance_eth_usdt_multiply)" times=1000000000000000000]
    
        coinbase_aave_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/AAVE/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_aave_usd_parse    [type="jsonparse" path="price"]
        coinbase_aave_usd_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]
        coinbase_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_aave_eth_divide    [type="divide" input="$(coinbase_aave_usd_multiply)" divisor="$(coinbase_eth_usd_multiply)" times=1000000000000000000]
    
        coingecko_aave_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/aave/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_aave_usd_parse    [type="jsonparse" path="price"]
        coingecko_aave_usd_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/bifrost-bridged-eth-bifrost/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]
        coingecko_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_aave_eth_divide    [type="divide" input="$(coingecko_aave_usd_multiply)" divisor="$(coingecko_eth_usd_multiply)" times=1000000000000000000]
    
        cryptocompare_aave_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/AAVE/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_aave_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_aave_usd_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_aave_eth_divide    [type="divide" input="$(cryptocompare_aave_usd_multiply)" divisor="$(cryptocompare_eth_usd_multiply)" times=1000000000000000000]
    
        kraken_aave_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/AAVE/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_aave_usd_parse    [type="jsonparse" path="price"]
        kraken_aave_usd_multiply [type="multiply" times=1000000000000000000]
    
        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]
        kraken_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        kraken_aave_eth_divide    [type="divide" input="$(kraken_aave_usd_multiply)" divisor="$(kraken_eth_usd_multiply)" times=1000000000000000000]
    
        okx_aave_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/AAVE/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_aave_usd_parse    [type="jsonparse" path="price"]
        okx_aave_usd_multiply [type="multiply" times=1000000000000000000]
    
        okx_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_eth_usd_parse    [type="jsonparse" path="price"]
        okx_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        okx_aave_eth_divide    [type="divide" input="$(okx_aave_usd_multiply)" divisor="$(okx_eth_usd_multiply)" times=1000000000000000000]
    
        median [type=median];
    
    alphavantage_aave_usd -> alphavantage_aave_usd_parse -> alphavantage_aave_usd_multiply -> alphavantage_aave_eth_divide
    alphavantage_eth_usd -> alphavantage_eth_usd_parse -> alphavantage_eth_usd_multiply -> alphavantage_aave_eth_divide
    binance_aave_usdt -> binance_aave_usdt_parse -> binance_aave_usdt_multiply -> binance_aave_eth_divide
    binance_eth_usdt -> binance_eth_usdt_parse -> binance_eth_usdt_multiply -> binance_aave_eth_divide
    coinbase_aave_usd -> coinbase_aave_usd_parse -> coinbase_aave_usd_multiply -> coinbase_aave_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_eth_usd_multiply -> coinbase_aave_eth_divide
    coingecko_aave_usd -> coingecko_aave_usd_parse -> coingecko_aave_usd_multiply -> coingecko_aave_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_eth_usd_multiply -> coingecko_aave_eth_divide
    cryptocompare_aave_usd -> cryptocompare_aave_usd_parse -> cryptocompare_aave_usd_multiply -> cryptocompare_aave_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_eth_usd_multiply -> cryptocompare_aave_eth_divide
    kraken_aave_usd -> kraken_aave_usd_parse -> kraken_aave_usd_multiply -> kraken_aave_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_eth_usd_multiply -> kraken_aave_eth_divide
    okx_aave_usd -> okx_aave_usd_parse -> okx_aave_usd_multiply -> okx_aave_eth_divide
    okx_eth_usd -> okx_eth_usd_parse -> okx_eth_usd_multiply -> okx_aave_eth_divide
    alphavantage_aave_eth_divide -> median;
    binance_aave_eth_divide -> median;
    coinbase_aave_eth_divide -> median;
    coingecko_aave_eth_divide -> median;
    cryptocompare_aave_eth_divide -> median;
    kraken_aave_eth_divide -> median;
    okx_aave_eth_divide -> median;
"""
