type = "offchainreporting"
schemaVersion = 1
name = "OCR Oracle: AVAIL / USD Price Feed"
externalJobID = "a57ee67c-5446-583c-b39c-2dd6d76d4c89"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "0xdee73d3785Ec99aA0E2e3dFa449c6B5f832aeff6"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://min-api.cryptocompare.com/data/price?fsym=AVAIL&tsyms=USD"];
    ds1_parse [type=jsonparse path="USD"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=avail&vs_currencies=usd"];
    ds2_parse [type=jsonparse path="avail,usd"];
    ds2_multiply [type=multiply times=100000000];
    median [type=median];
    
    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
"""
