type = "offchainreporting"
schemaVersion = 1
name = "BADGER / ETH"
externalJobID = "9c639f5f-d98e-5969-83e6-0259dd6da127"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        coinbase_badger_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/BADGER/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_badger_usd_parse    [type="jsonparse" path="price"]
        coinbase_badger_usd_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]
        coinbase_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_badger_eth_divide    [type="divide" input="$(coinbase_badger_usd_multiply)" divisor="$(coinbase_eth_usd_multiply)" times=1000000000000000000]
    
        coingecko_badger_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/badger-badger-badger/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_badger_usd_parse    [type="jsonparse" path="price"]
        coingecko_badger_usd_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/bifrost-bridged-eth-bifrost/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]
        coingecko_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_badger_eth_divide    [type="divide" input="$(coingecko_badger_usd_multiply)" divisor="$(coingecko_eth_usd_multiply)" times=1000000000000000000]
    
        cryptocompare_badger_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/BADGER/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_badger_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_badger_usd_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_badger_eth_divide    [type="divide" input="$(cryptocompare_badger_usd_multiply)" divisor="$(cryptocompare_eth_usd_multiply)" times=1000000000000000000]
    
        kraken_badger_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/BADGER/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_badger_usd_parse    [type="jsonparse" path="price"]
        kraken_badger_usd_multiply [type="multiply" times=1000000000000000000]
    
        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]
        kraken_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        kraken_badger_eth_divide    [type="divide" input="$(kraken_badger_usd_multiply)" divisor="$(kraken_eth_usd_multiply)" times=1000000000000000000]
    
        okx_badger_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/BADGER/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_badger_usd_parse    [type="jsonparse" path="price"]
        okx_badger_usd_multiply [type="multiply" times=1000000000000000000]
    
        okx_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_eth_usd_parse    [type="jsonparse" path="price"]
        okx_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        okx_badger_eth_divide    [type="divide" input="$(okx_badger_usd_multiply)" divisor="$(okx_eth_usd_multiply)" times=1000000000000000000]
    
        median [type=median];
    
    coinbase_badger_usd -> coinbase_badger_usd_parse -> coinbase_badger_usd_multiply -> coinbase_badger_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_eth_usd_multiply -> coinbase_badger_eth_divide
    coingecko_badger_usd -> coingecko_badger_usd_parse -> coingecko_badger_usd_multiply -> coingecko_badger_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_eth_usd_multiply -> coingecko_badger_eth_divide
    cryptocompare_badger_usd -> cryptocompare_badger_usd_parse -> cryptocompare_badger_usd_multiply -> cryptocompare_badger_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_eth_usd_multiply -> cryptocompare_badger_eth_divide
    kraken_badger_usd -> kraken_badger_usd_parse -> kraken_badger_usd_multiply -> kraken_badger_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_eth_usd_multiply -> kraken_badger_eth_divide
    okx_badger_usd -> okx_badger_usd_parse -> okx_badger_usd_multiply -> okx_badger_eth_divide
    okx_eth_usd -> okx_eth_usd_parse -> okx_eth_usd_multiply -> okx_badger_eth_divide
    coinbase_badger_eth_divide -> median;
    coingecko_badger_eth_divide -> median;
    cryptocompare_badger_eth_divide -> median;
    kraken_badger_eth_divide -> median;
    okx_badger_eth_divide -> median;
"""
