type = "offchainreporting"
schemaVersion = 1
name = "BAT / ETH"
externalJobID = "7d370063-f12f-5309-840a-ecb91b6e284c"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        binance_bat_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/BAT/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_bat_usdt_parse    [type="jsonparse" path="price"]

        binance_eth_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/ETH/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_eth_usdt_parse    [type="jsonparse" path="price"]

        binance_bat_eth_divide    [type="divide" input="$(binance_bat_usdt_parse)" divisor="$(binance_eth_usdt_parse)"]
        binance_bat_eth_divide_multiply [type="multiply" times=1000000000000000000]

        coinbase_bat_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/BAT/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_bat_usd_parse    [type="jsonparse" path="price"]

        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]

        coinbase_bat_eth_divide    [type="divide" input="$(coinbase_bat_usd_parse)" divisor="$(coinbase_eth_usd_parse)"]
        coinbase_bat_eth_divide_multiply [type="multiply" times=1000000000000000000]

        coingecko_bat_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/basic-attention-token/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_bat_usd_parse    [type="jsonparse" path="price"]

        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/ethereum/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]

        coingecko_bat_eth_divide    [type="divide" input="$(coingecko_bat_usd_parse)" divisor="$(coingecko_eth_usd_parse)"]
        coingecko_bat_eth_divide_multiply [type="multiply" times=1000000000000000000]

        cryptocompare_bat_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/BAT/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_bat_usd_parse    [type="jsonparse" path="price"]

        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]

        cryptocompare_bat_eth_divide    [type="divide" input="$(cryptocompare_bat_usd_parse)" divisor="$(cryptocompare_eth_usd_parse)"]
        cryptocompare_bat_eth_divide_multiply [type="multiply" times=1000000000000000000]

        kraken_bat_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/BAT/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_bat_usd_parse    [type="jsonparse" path="price"]

        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]

        kraken_bat_eth_divide    [type="divide" input="$(kraken_bat_usd_parse)" divisor="$(kraken_eth_usd_parse)"]
        kraken_bat_eth_divide_multiply [type="multiply" times=1000000000000000000]

        okx_bat_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/BAT/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_bat_usd_parse    [type="jsonparse" path="price"]

        okx_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_eth_usd_parse    [type="jsonparse" path="price"]

        okx_bat_eth_divide    [type="divide" input="$(okx_bat_usd_parse)" divisor="$(okx_eth_usd_parse)"]
        okx_bat_eth_divide_multiply [type="multiply" times=1000000000000000000]

        median [type=median];

    binance_bat_usdt -> binance_bat_usdt_parse -> binance_bat_eth_divide
    binance_eth_usdt -> binance_eth_usdt_parse -> binance_bat_eth_divide
    binance_bat_eth_divide -> binance_bat_eth_divide_multiply
    coinbase_bat_usd -> coinbase_bat_usd_parse -> coinbase_bat_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_bat_eth_divide
    coinbase_bat_eth_divide -> coinbase_bat_eth_divide_multiply
    coingecko_bat_usd -> coingecko_bat_usd_parse -> coingecko_bat_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_bat_eth_divide
    coingecko_bat_eth_divide -> coingecko_bat_eth_divide_multiply
    cryptocompare_bat_usd -> cryptocompare_bat_usd_parse -> cryptocompare_bat_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_bat_eth_divide
    cryptocompare_bat_eth_divide -> cryptocompare_bat_eth_divide_multiply
    kraken_bat_usd -> kraken_bat_usd_parse -> kraken_bat_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_bat_eth_divide
    kraken_bat_eth_divide -> kraken_bat_eth_divide_multiply
    okx_bat_usd -> okx_bat_usd_parse -> okx_bat_eth_divide
    okx_eth_usd -> okx_eth_usd_parse -> okx_bat_eth_divide
    okx_bat_eth_divide -> okx_bat_eth_divide_multiply
    binance_bat_eth_divide_multiply -> median;
    coinbase_bat_eth_divide_multiply -> median;
    coingecko_bat_eth_divide_multiply -> median;
    cryptocompare_bat_eth_divide_multiply -> median;
    kraken_bat_eth_divide_multiply -> median;
    okx_bat_eth_divide_multiply -> median;
"""
