type = "offchainreporting"
schemaVersion = 1
name = "BTC / BNB"
externalJobID = "3adae159-4276-58a3-8291-01fae3dc3e60"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        binance_btc_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/BTC/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_btc_usdt_parse    [type="jsonparse" path="price"]
        binance_btc_usdt_multiply [type="multiply" times=1000000000000000000]
    
        binance_bnb_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/BNB/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_bnb_usdt_parse    [type="jsonparse" path="price"]
        binance_bnb_usdt_multiply [type="multiply" times=1000000000000000000]
    
        binance_btc_bnb_divide    [type="divide" input="$(binance_btc_usdt_multiply)" divisor="$(binance_bnb_usdt_multiply)" times=1000000000000000000]
    
        coinbase_btc_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/BTC/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_btc_usd_parse    [type="jsonparse" path="price"]
        coinbase_btc_usd_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_bnb_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/BNB/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_bnb_usd_parse    [type="jsonparse" path="price"]
        coinbase_bnb_usd_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_btc_bnb_divide    [type="divide" input="$(coinbase_btc_usd_multiply)" divisor="$(coinbase_bnb_usd_multiply)" times=1000000000000000000]
    
        coingecko_btc_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/batcat/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_btc_usd_parse    [type="jsonparse" path="price"]
        coingecko_btc_usd_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_bnb_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/bifrost-bridged-bnb-bifrost/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_bnb_usd_parse    [type="jsonparse" path="price"]
        coingecko_bnb_usd_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_btc_bnb_divide    [type="divide" input="$(coingecko_btc_usd_multiply)" divisor="$(coingecko_bnb_usd_multiply)" times=1000000000000000000]
    
        cryptocompare_btc_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/BTC/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_btc_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_btc_usd_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_bnb_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/BNB/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_bnb_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_bnb_usd_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_btc_bnb_divide    [type="divide" input="$(cryptocompare_btc_usd_multiply)" divisor="$(cryptocompare_bnb_usd_multiply)" times=1000000000000000000]
    
        kraken_btc_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/XBT/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_btc_usd_parse    [type="jsonparse" path="price"]
        kraken_btc_usd_multiply [type="multiply" times=1000000000000000000]
    
        kraken_bnb_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/BNB/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_bnb_usd_parse    [type="jsonparse" path="price"]
        kraken_bnb_usd_multiply [type="multiply" times=1000000000000000000]
    
        kraken_btc_bnb_divide    [type="divide" input="$(kraken_btc_usd_multiply)" divisor="$(kraken_bnb_usd_multiply)" times=1000000000000000000]
    
        okx_btc_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/BTC/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_btc_usd_parse    [type="jsonparse" path="price"]
        okx_btc_usd_multiply [type="multiply" times=1000000000000000000]
    
        okx_bnb_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/BNB/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_bnb_usd_parse    [type="jsonparse" path="price"]
        okx_bnb_usd_multiply [type="multiply" times=1000000000000000000]
    
        okx_btc_bnb_divide    [type="divide" input="$(okx_btc_usd_multiply)" divisor="$(okx_bnb_usd_multiply)" times=1000000000000000000]
    
        median [type=median];
    
    binance_btc_usdt -> binance_btc_usdt_parse -> binance_btc_usdt_multiply -> binance_btc_bnb_divide
    binance_bnb_usdt -> binance_bnb_usdt_parse -> binance_bnb_usdt_multiply -> binance_btc_bnb_divide
    coinbase_btc_usd -> coinbase_btc_usd_parse -> coinbase_btc_usd_multiply -> coinbase_btc_bnb_divide
    coinbase_bnb_usd -> coinbase_bnb_usd_parse -> coinbase_bnb_usd_multiply -> coinbase_btc_bnb_divide
    coingecko_btc_usd -> coingecko_btc_usd_parse -> coingecko_btc_usd_multiply -> coingecko_btc_bnb_divide
    coingecko_bnb_usd -> coingecko_bnb_usd_parse -> coingecko_bnb_usd_multiply -> coingecko_btc_bnb_divide
    cryptocompare_btc_usd -> cryptocompare_btc_usd_parse -> cryptocompare_btc_usd_multiply -> cryptocompare_btc_bnb_divide
    cryptocompare_bnb_usd -> cryptocompare_bnb_usd_parse -> cryptocompare_bnb_usd_multiply -> cryptocompare_btc_bnb_divide
    kraken_btc_usd -> kraken_btc_usd_parse -> kraken_btc_usd_multiply -> kraken_btc_bnb_divide
    kraken_bnb_usd -> kraken_bnb_usd_parse -> kraken_bnb_usd_multiply -> kraken_btc_bnb_divide
    okx_btc_usd -> okx_btc_usd_parse -> okx_btc_usd_multiply -> okx_btc_bnb_divide
    okx_bnb_usd -> okx_bnb_usd_parse -> okx_bnb_usd_multiply -> okx_btc_bnb_divide
    binance_btc_bnb_divide -> median;
    coinbase_btc_bnb_divide -> median;
    coingecko_btc_bnb_divide -> median;
    cryptocompare_btc_bnb_divide -> median;
    kraken_btc_bnb_divide -> median;
    okx_btc_bnb_divide -> median;
"""
