type = "offchainreporting"
schemaVersion = 1
name = "Calculated stMATIC / USD"
externalJobID = "ca9e11e3-eb06-421c-9df8-ad4728b329d5"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=lido-staked-matic&vs_currencies=usd"];
    ds1_parse [type=jsonparse path="lido-staked-matic.usd"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?symbol=stMATIC&CMC_PRO_API_KEY=12913f9a-4d3d-4529-876a-8f2dd395c95f"];
    ds2_parse [type=jsonparse path="unknown"];
    ds2_multiply [type=multiply times=100000000];
    median [type=median];

    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
"""
