type = "offchainreporting"
schemaVersion = 1
name = "Calculated SAVAX / USD"
externalJobID = "8aaa7853-e9a4-48ce-89bf-ee23f132bc03"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=benqi-liquid-staked-avax&vs_currencies=usd"];
    ds1_parse [type=jsonparse path="benqi-liquid-staked-avax.usd"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="https://data.chain.link/feeds/bsc/mainnet/calculated-savax-usd"];
    ds2_parse [type=jsonparse path="unknown"];
    ds2_multiply [type=multiply times=100000000];
    median [type=median];

    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
"""
