type = "offchainreporting"
schemaVersion = 1
name = "COMP / ETH"
externalJobID = "8455d04a-4a8d-5b9e-ba30-90b874563097"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        binance_comp_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/COMP/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_comp_usdt_parse    [type="jsonparse" path="price"]
        binance_comp_usdt_multiply [type="multiply" times=1000000000000000000]
    
        binance_eth_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/ETH/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_eth_usdt_parse    [type="jsonparse" path="price"]
        binance_eth_usdt_multiply [type="multiply" times=1000000000000000000]
    
        binance_comp_eth_divide    [type="divide" input="$(binance_comp_usdt_multiply)" divisor="$(binance_eth_usdt_multiply)" times=1000000000000000000]
    
        coinbase_comp_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/COMP/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_comp_usd_parse    [type="jsonparse" path="price"]
        coinbase_comp_usd_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]
        coinbase_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_comp_eth_divide    [type="divide" input="$(coinbase_comp_usd_multiply)" divisor="$(coinbase_eth_usd_multiply)" times=1000000000000000000]
    
        coingecko_comp_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/compound-governance-token/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_comp_usd_parse    [type="jsonparse" path="price"]
        coingecko_comp_usd_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/bifrost-bridged-eth-bifrost/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]
        coingecko_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_comp_eth_divide    [type="divide" input="$(coingecko_comp_usd_multiply)" divisor="$(coingecko_eth_usd_multiply)" times=1000000000000000000]
    
        cryptocompare_comp_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/COMP/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_comp_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_comp_usd_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_comp_eth_divide    [type="divide" input="$(cryptocompare_comp_usd_multiply)" divisor="$(cryptocompare_eth_usd_multiply)" times=1000000000000000000]
    
        kraken_comp_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/COMP/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_comp_usd_parse    [type="jsonparse" path="price"]
        kraken_comp_usd_multiply [type="multiply" times=1000000000000000000]
    
        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]
        kraken_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        kraken_comp_eth_divide    [type="divide" input="$(kraken_comp_usd_multiply)" divisor="$(kraken_eth_usd_multiply)" times=1000000000000000000]
    
        okx_comp_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/COMP/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_comp_usd_parse    [type="jsonparse" path="price"]
        okx_comp_usd_multiply [type="multiply" times=1000000000000000000]
    
        okx_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_eth_usd_parse    [type="jsonparse" path="price"]
        okx_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        okx_comp_eth_divide    [type="divide" input="$(okx_comp_usd_multiply)" divisor="$(okx_eth_usd_multiply)" times=1000000000000000000]
    
        median [type=median];
    
    binance_comp_usdt -> binance_comp_usdt_parse -> binance_comp_usdt_multiply -> binance_comp_eth_divide
    binance_eth_usdt -> binance_eth_usdt_parse -> binance_eth_usdt_multiply -> binance_comp_eth_divide
    coinbase_comp_usd -> coinbase_comp_usd_parse -> coinbase_comp_usd_multiply -> coinbase_comp_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_eth_usd_multiply -> coinbase_comp_eth_divide
    coingecko_comp_usd -> coingecko_comp_usd_parse -> coingecko_comp_usd_multiply -> coingecko_comp_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_eth_usd_multiply -> coingecko_comp_eth_divide
    cryptocompare_comp_usd -> cryptocompare_comp_usd_parse -> cryptocompare_comp_usd_multiply -> cryptocompare_comp_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_eth_usd_multiply -> cryptocompare_comp_eth_divide
    kraken_comp_usd -> kraken_comp_usd_parse -> kraken_comp_usd_multiply -> kraken_comp_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_eth_usd_multiply -> kraken_comp_eth_divide
    okx_comp_usd -> okx_comp_usd_parse -> okx_comp_usd_multiply -> okx_comp_eth_divide
    okx_eth_usd -> okx_eth_usd_parse -> okx_eth_usd_multiply -> okx_comp_eth_divide
    binance_comp_eth_divide -> median;
    coinbase_comp_eth_divide -> median;
    coingecko_comp_eth_divide -> median;
    cryptocompare_comp_eth_divide -> median;
    kraken_comp_eth_divide -> median;
    okx_comp_eth_divide -> median;
"""
