type = "offchainreporting"
schemaVersion = 1
name = "CVX / ETH"
externalJobID = "d3255aae-be2c-5ea3-9735-e0689503e951"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        coinbase_cvx_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/CVX/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_cvx_usd_parse    [type="jsonparse" path="price"]
    
        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]
    
        coinbase_cvx_eth_divide    [type="divide" input="$(coinbase_cvx_usd_parse)" divisor="$(coinbase_eth_usd_parse)"]
        coinbase_cvx_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_cvx_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/convex-finance/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_cvx_usd_parse    [type="jsonparse" path="price"]
    
        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/bifrost-bridged-eth-bifrost/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]
    
        coingecko_cvx_eth_divide    [type="divide" input="$(coingecko_cvx_usd_parse)" divisor="$(coingecko_eth_usd_parse)"]
        coingecko_cvx_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_cvx_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/CVX/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_cvx_usd_parse    [type="jsonparse" path="price"]
    
        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]
    
        cryptocompare_cvx_eth_divide    [type="divide" input="$(cryptocompare_cvx_usd_parse)" divisor="$(cryptocompare_eth_usd_parse)"]
        cryptocompare_cvx_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        kraken_cvx_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/CVX/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_cvx_usd_parse    [type="jsonparse" path="price"]
    
        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]
    
        kraken_cvx_eth_divide    [type="divide" input="$(kraken_cvx_usd_parse)" divisor="$(kraken_eth_usd_parse)"]
        kraken_cvx_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        okx_cvx_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/CVX/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_cvx_usd_parse    [type="jsonparse" path="price"]
    
        okx_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_eth_usd_parse    [type="jsonparse" path="price"]
    
        okx_cvx_eth_divide    [type="divide" input="$(okx_cvx_usd_parse)" divisor="$(okx_eth_usd_parse)"]
        okx_cvx_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        median [type=median];
    
    coinbase_cvx_usd -> coinbase_cvx_usd_parse -> coinbase_cvx_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_cvx_eth_divide
    coinbase_cvx_eth_divide -> coinbase_cvx_eth_divide_multiply
    coingecko_cvx_usd -> coingecko_cvx_usd_parse -> coingecko_cvx_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_cvx_eth_divide
    coingecko_cvx_eth_divide -> coingecko_cvx_eth_divide_multiply
    cryptocompare_cvx_usd -> cryptocompare_cvx_usd_parse -> cryptocompare_cvx_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_cvx_eth_divide
    cryptocompare_cvx_eth_divide -> cryptocompare_cvx_eth_divide_multiply
    kraken_cvx_usd -> kraken_cvx_usd_parse -> kraken_cvx_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_cvx_eth_divide
    kraken_cvx_eth_divide -> kraken_cvx_eth_divide_multiply
    okx_cvx_usd -> okx_cvx_usd_parse -> okx_cvx_eth_divide
    okx_eth_usd -> okx_eth_usd_parse -> okx_cvx_eth_divide
    okx_cvx_eth_divide -> okx_cvx_eth_divide_multiply
    coinbase_cvx_eth_divide_multiply -> median;
    coingecko_cvx_eth_divide_multiply -> median;
    cryptocompare_cvx_eth_divide_multiply -> median;
    kraken_cvx_eth_divide_multiply -> median;
    okx_cvx_eth_divide_multiply -> median;
"""
