type = "offchainreporting"
schemaVersion = 1
name = "ENJ / ETH"
externalJobID = "be21ebea-c14a-50dc-a9d8-d2cb61eba382"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        binance_enj_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/ENJ/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_enj_usdt_parse    [type="jsonparse" path="price"]
    
        binance_eth_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/ETH/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_eth_usdt_parse    [type="jsonparse" path="price"]
    
        binance_enj_eth_divide    [type="divide" input="$(binance_enj_usdt_parse)" divisor="$(binance_eth_usdt_parse)"]
        binance_enj_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_enj_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ENJ/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_enj_usd_parse    [type="jsonparse" path="price"]
    
        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]
    
        coinbase_enj_eth_divide    [type="divide" input="$(coinbase_enj_usd_parse)" divisor="$(coinbase_eth_usd_parse)"]
        coinbase_enj_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_enj_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/enjincoin/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_enj_usd_parse    [type="jsonparse" path="price"]
    
        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/bifrost-bridged-eth-bifrost/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]
    
        coingecko_enj_eth_divide    [type="divide" input="$(coingecko_enj_usd_parse)" divisor="$(coingecko_eth_usd_parse)"]
        coingecko_enj_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_enj_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ENJ/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_enj_usd_parse    [type="jsonparse" path="price"]
    
        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]
    
        cryptocompare_enj_eth_divide    [type="divide" input="$(cryptocompare_enj_usd_parse)" divisor="$(cryptocompare_eth_usd_parse)"]
        cryptocompare_enj_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        kraken_enj_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ENJ/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_enj_usd_parse    [type="jsonparse" path="price"]
    
        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]
    
        kraken_enj_eth_divide    [type="divide" input="$(kraken_enj_usd_parse)" divisor="$(kraken_eth_usd_parse)"]
        kraken_enj_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        okx_enj_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/ENJ/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_enj_usd_parse    [type="jsonparse" path="price"]
    
        okx_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_eth_usd_parse    [type="jsonparse" path="price"]
    
        okx_enj_eth_divide    [type="divide" input="$(okx_enj_usd_parse)" divisor="$(okx_eth_usd_parse)"]
        okx_enj_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        median [type=median];
    
    binance_enj_usdt -> binance_enj_usdt_parse -> binance_enj_eth_divide
    binance_eth_usdt -> binance_eth_usdt_parse -> binance_enj_eth_divide
    binance_enj_eth_divide -> binance_enj_eth_divide_multiply
    coinbase_enj_usd -> coinbase_enj_usd_parse -> coinbase_enj_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_enj_eth_divide
    coinbase_enj_eth_divide -> coinbase_enj_eth_divide_multiply
    coingecko_enj_usd -> coingecko_enj_usd_parse -> coingecko_enj_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_enj_eth_divide
    coingecko_enj_eth_divide -> coingecko_enj_eth_divide_multiply
    cryptocompare_enj_usd -> cryptocompare_enj_usd_parse -> cryptocompare_enj_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_enj_eth_divide
    cryptocompare_enj_eth_divide -> cryptocompare_enj_eth_divide_multiply
    kraken_enj_usd -> kraken_enj_usd_parse -> kraken_enj_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_enj_eth_divide
    kraken_enj_eth_divide -> kraken_enj_eth_divide_multiply
    okx_enj_usd -> okx_enj_usd_parse -> okx_enj_eth_divide
    okx_eth_usd -> okx_eth_usd_parse -> okx_enj_eth_divide
    okx_enj_eth_divide -> okx_enj_eth_divide_multiply
    binance_enj_eth_divide_multiply -> median;
    coinbase_enj_eth_divide_multiply -> median;
    coingecko_enj_eth_divide_multiply -> median;
    cryptocompare_enj_eth_divide_multiply -> median;
    kraken_enj_eth_divide_multiply -> median;
    okx_enj_eth_divide_multiply -> median;
"""
