type = "offchainreporting"
schemaVersion = 1
name = "OCR Oracle: EURC / USD Price Feed"
externalJobID = "a1415b38-fb04-5589-8d59-41762599fb18"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "0x9bB910Cece83B92523a07D160D0f7731Ca01ff48"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://min-api.cryptocompare.com/data/price?fsym=EURC&tsyms=USD"];
    ds1_parse [type=jsonparse path="USD"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=euro-coin&vs_currencies=usd"];
    ds2_parse [type=jsonparse path="euro-coin,usd"];
    ds2_multiply [type=multiply times=100000000];
    ds3 [type=http method=GET url="https://api.coinbase.com/v2/prices/EURC-USD/spot"];
    ds3_parse [type=jsonparse path="USD"];
    ds3_multiply [type=multiply times=100000000];
    median [type=median];
    
    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds3 -> ds3_parse -> ds3_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
    ds3_multiply -> median;
"""
