type = "offchainreporting"
schemaVersion = 1
name = "OCR Oracle: GBP / USD Price Feed"
externalJobID = "01c89916-4a87-5392-8581-c6ef39206f36"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "0x8046292aC587B4f24C0EeC181Df2fe21AF65358C"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://api.binance.com/api/v3/ticker/price?symbol=GBPUSDT"];
    ds1_parse [type=jsonparse path="price"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="https://min-api.cryptocompare.com/data/price?fsym=GBP&tsyms=USD"];
    ds2_parse [type=jsonparse path="USD"];
    ds2_multiply [type=multiply times=100000000];
    ds3 [type=http method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=monerium-gbp-emoney&vs_currencies=usd"];
    ds3_parse [type=jsonparse path="monerium-gbp-emoney,usd"];
    ds3_multiply [type=multiply times=100000000];
    ds4 [type=http method=GET url="https://api.coinbase.com/v2/prices/GBP-USD/spot"];
    ds4_parse [type=jsonparse path="data,amount"];
    ds4_multiply [type=multiply times=100000000];
    ds5 [type=http method=GET url="https://api.kraken.com/0/public/Ticker?pair=GBPUSD"];
    ds5_parse [type=jsonparse path="result,ZGBPZUSD,c,0"];
    ds5_multiply [type=multiply times=100000000];
    ds6 [type=http method=GET url="https://api.frankfurter.app/latest?from=GBP&to=USD"];
    ds6_parse [type=jsonparse path="rates,USD"];
    ds6_multiply [type=multiply times=100000000];
    median [type=median];
    
    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds3 -> ds3_parse -> ds3_multiply;
    ds4 -> ds4_parse -> ds4_multiply;
    ds5 -> ds5_parse -> ds5_multiply;
    ds6 -> ds6_parse -> ds6_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
    ds3_multiply -> median;
    ds4_multiply -> median;
    ds5_multiply -> median;
    ds6_multiply -> median;
"""
