type = "offchainreporting"
schemaVersion = 1
name = "ILV / ETH"
externalJobID = "fc9a4f3e-4910-4375-b63a-c8f9544c002e"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://coincodex.com/api/v1/coins/get_coin_ranges_currency/ILV?currency=ETH"];
    ds1_parse [type=jsonparse path="unknown"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="https://simpleswap.io/api/v4/estimates?amount=1&fixed=false&networkFrom=base&networkTo=eth&tickerFrom=eth&tickerTo=ilv&reverse=false"];
    ds2_parse [type=jsonparse path="unknown"];
    ds2_multiply [type=multiply times=100000000];
    ds3 [type=http method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=illuvium&vs_currencies=eth"];
    ds3_parse [type=jsonparse path="illuvium.eth"];
    ds3_multiply [type=multiply times=100000000];
    median [type=median];

    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds3 -> ds3_parse -> ds3_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
    ds3_multiply -> median;
"""
