type = "offchainreporting"
schemaVersion = 1
name = "LINK / ETH"
externalJobID = "25f4c6b8-4eb1-5e25-a5da-ae4414a1932a"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        binance_link_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/LINK/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_link_usdt_parse    [type="jsonparse" path="price"]
        binance_link_usdt_multiply [type="multiply" times=1000000000000000000]
    
        binance_eth_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/ETH/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_eth_usdt_parse    [type="jsonparse" path="price"]
        binance_eth_usdt_multiply [type="multiply" times=1000000000000000000]
    
        binance_link_eth_divide    [type="divide" input="$(binance_link_usdt_multiply)" divisor="$(binance_eth_usdt_multiply)" times=1000000000000000000]
    
        coinbase_link_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/LINK/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_link_usd_parse    [type="jsonparse" path="price"]
        coinbase_link_usd_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]
        coinbase_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_link_eth_divide    [type="divide" input="$(coinbase_link_usd_multiply)" divisor="$(coinbase_eth_usd_multiply)" times=1000000000000000000]
    
        coingecko_link_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/chainlink/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_link_usd_parse    [type="jsonparse" path="price"]
        coingecko_link_usd_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/bifrost-bridged-eth-bifrost/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]
        coingecko_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_link_eth_divide    [type="divide" input="$(coingecko_link_usd_multiply)" divisor="$(coingecko_eth_usd_multiply)" times=1000000000000000000]
    
        cryptocompare_link_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/LINK/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_link_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_link_usd_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_link_eth_divide    [type="divide" input="$(cryptocompare_link_usd_multiply)" divisor="$(cryptocompare_eth_usd_multiply)" times=1000000000000000000]
    
        kraken_link_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/LINK/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_link_usd_parse    [type="jsonparse" path="price"]
        kraken_link_usd_multiply [type="multiply" times=1000000000000000000]
    
        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]
        kraken_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        kraken_link_eth_divide    [type="divide" input="$(kraken_link_usd_multiply)" divisor="$(kraken_eth_usd_multiply)" times=1000000000000000000]
    
        okx_link_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/LINK/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_link_usd_parse    [type="jsonparse" path="price"]
        okx_link_usd_multiply [type="multiply" times=1000000000000000000]
    
        okx_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_eth_usd_parse    [type="jsonparse" path="price"]
        okx_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        okx_link_eth_divide    [type="divide" input="$(okx_link_usd_multiply)" divisor="$(okx_eth_usd_multiply)" times=1000000000000000000]
    
        median [type=median];
    
    binance_link_usdt -> binance_link_usdt_parse -> binance_link_usdt_multiply -> binance_link_eth_divide
    binance_eth_usdt -> binance_eth_usdt_parse -> binance_eth_usdt_multiply -> binance_link_eth_divide
    coinbase_link_usd -> coinbase_link_usd_parse -> coinbase_link_usd_multiply -> coinbase_link_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_eth_usd_multiply -> coinbase_link_eth_divide
    coingecko_link_usd -> coingecko_link_usd_parse -> coingecko_link_usd_multiply -> coingecko_link_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_eth_usd_multiply -> coingecko_link_eth_divide
    cryptocompare_link_usd -> cryptocompare_link_usd_parse -> cryptocompare_link_usd_multiply -> cryptocompare_link_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_eth_usd_multiply -> cryptocompare_link_eth_divide
    kraken_link_usd -> kraken_link_usd_parse -> kraken_link_usd_multiply -> kraken_link_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_eth_usd_multiply -> kraken_link_eth_divide
    okx_link_usd -> okx_link_usd_parse -> okx_link_usd_multiply -> okx_link_eth_divide
    okx_eth_usd -> okx_eth_usd_parse -> okx_eth_usd_multiply -> okx_link_eth_divide
    binance_link_eth_divide -> median;
    coinbase_link_eth_divide -> median;
    coingecko_link_eth_divide -> median;
    cryptocompare_link_eth_divide -> median;
    kraken_link_eth_divide -> median;
    okx_link_eth_divide -> median;
"""
