type = "offchainreporting"
schemaVersion = 1
name = "MANA / ETH"
externalJobID = "8db28226-c535-53e3-a72b-e495dfe1d32e"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        binance_mana_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/MANA/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_mana_usdt_parse    [type="jsonparse" path="price"]
    
        binance_eth_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/ETH/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_eth_usdt_parse    [type="jsonparse" path="price"]
    
        binance_mana_eth_divide    [type="divide" input="$(binance_mana_usdt_parse)" divisor="$(binance_eth_usdt_parse)"]
        binance_mana_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_mana_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/MANA/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_mana_usd_parse    [type="jsonparse" path="price"]
    
        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]
    
        coinbase_mana_eth_divide    [type="divide" input="$(coinbase_mana_usd_parse)" divisor="$(coinbase_eth_usd_parse)"]
        coinbase_mana_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_mana_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/decentraland/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_mana_usd_parse    [type="jsonparse" path="price"]
    
        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/bifrost-bridged-eth-bifrost/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]
    
        coingecko_mana_eth_divide    [type="divide" input="$(coingecko_mana_usd_parse)" divisor="$(coingecko_eth_usd_parse)"]
        coingecko_mana_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_mana_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/MANA/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_mana_usd_parse    [type="jsonparse" path="price"]
    
        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]
    
        cryptocompare_mana_eth_divide    [type="divide" input="$(cryptocompare_mana_usd_parse)" divisor="$(cryptocompare_eth_usd_parse)"]
        cryptocompare_mana_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        kraken_mana_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/MANA/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_mana_usd_parse    [type="jsonparse" path="price"]
    
        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]
    
        kraken_mana_eth_divide    [type="divide" input="$(kraken_mana_usd_parse)" divisor="$(kraken_eth_usd_parse)"]
        kraken_mana_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        okx_mana_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/MANA/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_mana_usd_parse    [type="jsonparse" path="price"]
    
        okx_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_eth_usd_parse    [type="jsonparse" path="price"]
    
        okx_mana_eth_divide    [type="divide" input="$(okx_mana_usd_parse)" divisor="$(okx_eth_usd_parse)"]
        okx_mana_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        median [type=median];
    
    binance_mana_usdt -> binance_mana_usdt_parse -> binance_mana_eth_divide
    binance_eth_usdt -> binance_eth_usdt_parse -> binance_mana_eth_divide
    binance_mana_eth_divide -> binance_mana_eth_divide_multiply
    coinbase_mana_usd -> coinbase_mana_usd_parse -> coinbase_mana_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_mana_eth_divide
    coinbase_mana_eth_divide -> coinbase_mana_eth_divide_multiply
    coingecko_mana_usd -> coingecko_mana_usd_parse -> coingecko_mana_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_mana_eth_divide
    coingecko_mana_eth_divide -> coingecko_mana_eth_divide_multiply
    cryptocompare_mana_usd -> cryptocompare_mana_usd_parse -> cryptocompare_mana_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_mana_eth_divide
    cryptocompare_mana_eth_divide -> cryptocompare_mana_eth_divide_multiply
    kraken_mana_usd -> kraken_mana_usd_parse -> kraken_mana_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_mana_eth_divide
    kraken_mana_eth_divide -> kraken_mana_eth_divide_multiply
    okx_mana_usd -> okx_mana_usd_parse -> okx_mana_eth_divide
    okx_eth_usd -> okx_eth_usd_parse -> okx_mana_eth_divide
    okx_mana_eth_divide -> okx_mana_eth_divide_multiply
    binance_mana_eth_divide_multiply -> median;
    coinbase_mana_eth_divide_multiply -> median;
    coingecko_mana_eth_divide_multiply -> median;
    cryptocompare_mana_eth_divide_multiply -> median;
    kraken_mana_eth_divide_multiply -> median;
    okx_mana_eth_divide_multiply -> median;
"""
