type = "offchainreporting"
schemaVersion = 1
name = "OCR Oracle: NZD / USD Price Feed"
externalJobID = "dce0500c-5d3b-54fb-95f5-52774565aa51"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "0x7453784e9415"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://min-api.cryptocompare.com/data/price?fsym=NZD&tsyms=USD"];
    ds1_parse [type=jsonparse path="USD"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="https://api.coinbase.com/v2/prices/NZD-USD/spot"];
    ds2_parse [type=jsonparse path="USD"];
    ds2_multiply [type=multiply times=100000000];
    ds3 [type=http method=GET url="https://api.frankfurter.app/latest?from=NZD&to=USD"];
    ds3_parse [type=jsonparse path="USD"];
    ds3_multiply [type=multiply times=100000000];
    median [type=median];
    
    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds3 -> ds3_parse -> ds3_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
    ds3_multiply -> median;
"""
