type = "offchainreporting"
schemaVersion = 1
name = "OETH / ETH"
externalJobID = "655c3bd5-2d42-5c00-82f7-1a76dfb3e1b1"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        coingecko_oeth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/bifrost-bridged-eth-bifrost/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_oeth_usd_parse    [type="jsonparse" path="price"]
    
        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/orbit-bridge-klaytn-ethereum/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]
    
        coingecko_oeth_eth_divide    [type="divide" input="$(coingecko_oeth_usd_parse)" divisor="$(coingecko_eth_usd_parse)"]
        coingecko_oeth_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        median [type=median];
    
    coingecko_oeth_usd -> coingecko_oeth_usd_parse -> coingecko_oeth_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_oeth_eth_divide
    coingecko_oeth_eth_divide -> coingecko_oeth_eth_divide_multiply
    coingecko_oeth_eth_divide_multiply -> median;
"""
