type = "offchainreporting"
schemaVersion = 1
name = "OCR Oracle: ONT / USD Price Feed"
externalJobID = "dfde41f3-f161-50b4-a042-07bc5fbe2d23"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "0x438b59060874"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://api.binance.com/api/v3/ticker/price?symbol=ONTUSDT"];
    ds1_parse [type=jsonparse path="price"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="https://min-api.cryptocompare.com/data/price?fsym=ONT&tsyms=USD"];
    ds2_parse [type=jsonparse path="USD"];
    ds2_multiply [type=multiply times=100000000];
    ds3 [type=http method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=binance-peg-ontology&vs_currencies=usd"];
    ds3_parse [type=jsonparse path="binance-peg-ontology,usd"];
    ds3_multiply [type=multiply times=100000000];
    ds4 [type=http method=GET url="https://api.coinbase.com/v2/prices/ONT-USD/spot"];
    ds4_parse [type=jsonparse path="USD"];
    ds4_multiply [type=multiply times=100000000];
    median [type=median];
    
    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds3 -> ds3_parse -> ds3_multiply;
    ds4 -> ds4_parse -> ds4_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
    ds3_multiply -> median;
    ds4_multiply -> median;
"""
