type = "offchainreporting"
schemaVersion = 1
name = "QQQ / USD"
externalJobID = "9fb78587-a964-5d5e-838c-df945687f32e"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://query1.finance.yahoo.com/v8/finance/chart/QQQ?interval=1d headers="[\\"User-Agent\\", \\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36\\"]"];
    ds1_parse [type=jsonparse path="chart,result,0,meta,regularMarketPrice"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/invesco-qqq-etf-ondo-tokenized-etf/USD"];
    ds2_parse [type=jsonparse path="price"];
    ds2_multiply [type=multiply times=100000000];
    median [type=median];

    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
"""
