type = "offchainreporting"
schemaVersion = 1
name = "OCR Oracle: RPL / USD Price Feed"
externalJobID = "1ddd535c-f034-5c29-a240-479324c81c83"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "0x25DB3AC56F2eE0157A83861f96E93a89dbCA289B"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://api.binance.com/api/v3/ticker/price?symbol=RPLUSDT"];
    ds1_parse [type=jsonparse path="price"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="https://min-api.cryptocompare.com/data/price?fsym=RPL&tsyms=USD"];
    ds2_parse [type=jsonparse path="USD"];
    ds2_multiply [type=multiply times=100000000];
    ds3 [type=http method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=rocket-pool&vs_currencies=usd"];
    ds3_parse [type=jsonparse path="rocket-pool,usd"];
    ds3_multiply [type=multiply times=100000000];
    ds4 [type=http method=GET url="https://api.coinbase.com/v2/prices/RPL-USD/spot"];
    ds4_parse [type=jsonparse path="data,amount"];
    ds4_multiply [type=multiply times=100000000];
    ds5 [type=http method=GET url="https://api.kraken.com/0/public/Ticker?pair=RPLUSD"];
    ds5_parse [type=jsonparse path="result,RPLUSD,c,0"];
    ds5_multiply [type=multiply times=100000000];
    ds6 [type=http method=GET url="https://www.okx.com/api/v5/market/ticker?instId=RPL-USD"];
    ds6_parse [type=jsonparse path="data,0,last"];
    ds6_multiply [type=multiply times=100000000];
    median [type=median];
    
    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds3 -> ds3_parse -> ds3_multiply;
    ds4 -> ds4_parse -> ds4_multiply;
    ds5 -> ds5_parse -> ds5_multiply;
    ds6 -> ds6_parse -> ds6_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
    ds3_multiply -> median;
    ds4_multiply -> median;
    ds5_multiply -> median;
    ds6_multiply -> median;
"""
