type = "offchainreporting"
schemaVersion = 1
name = "rsETH / ETH Exchange Rate"
externalJobID = "55139f4c-7e4a-4369-a469-26028b95caaf"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=kelp-dao-restaked-eth&vs_currencies=eth"];
    ds1_parse [type=jsonparse path="kelp-dao-restaked-eth.eth"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="https://data.chain.link/feeds/scroll/mainnet/rseth-eth-exchange-rate"];
    ds2_parse [type=jsonparse path="unknown"];
    ds2_multiply [type=multiply times=100000000];
    median [type=median];

    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
"""
