type = "offchainreporting"
schemaVersion = 1
name = "SEK / USD"
externalJobID = "1200f134-f190-5666-907b-80e95fcb6cef"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds3 [type=http method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/SEK/USD"];
    ds3_parse [type=jsonparse path="price"];
    ds3_multiply [type=multiply times=100000000];
    ds4 [type=http method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/frankfurter/SEK/USD"];
    ds4_parse [type=jsonparse path="price"];
    ds4_multiply [type=multiply times=100000000];
    median [type=median];

    ds3 -> ds3_parse -> ds3_multiply;
    ds4 -> ds4_parse -> ds4_multiply;
    ds3_multiply -> median;
    ds4_multiply -> median;
"""
