type = "offchainreporting"
schemaVersion = 1
name = "SHIB / ETH"
externalJobID = "13392d03-ba83-5107-a98d-bb9837d5ff6d"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        binance_shib_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/SHIB/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_shib_usdt_parse    [type="jsonparse" path="price"]

        binance_eth_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/ETH/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_eth_usdt_parse    [type="jsonparse" path="price"]

        binance_shib_eth_divide    [type="divide" input="$(binance_shib_usdt_parse)" divisor="$(binance_eth_usdt_parse)"]
        binance_shib_eth_divide_multiply [type="multiply" times=1000000000000000000]

        coinbase_shib_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/SHIB/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_shib_usd_parse    [type="jsonparse" path="price"]

        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]

        coinbase_shib_eth_divide    [type="divide" input="$(coinbase_shib_usd_parse)" divisor="$(coinbase_eth_usd_parse)"]
        coinbase_shib_eth_divide_multiply [type="multiply" times=1000000000000000000]

        coingecko_shib_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/binance-peg-shib/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_shib_usd_parse    [type="jsonparse" path="price"]

        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/ethereum/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]

        coingecko_shib_eth_divide    [type="divide" input="$(coingecko_shib_usd_parse)" divisor="$(coingecko_eth_usd_parse)"]
        coingecko_shib_eth_divide_multiply [type="multiply" times=1000000000000000000]

        cryptocompare_shib_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/SHIB/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_shib_usd_parse    [type="jsonparse" path="price"]

        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]

        cryptocompare_shib_eth_divide    [type="divide" input="$(cryptocompare_shib_usd_parse)" divisor="$(cryptocompare_eth_usd_parse)"]
        cryptocompare_shib_eth_divide_multiply [type="multiply" times=1000000000000000000]

        kraken_shib_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/SHIB/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_shib_usd_parse    [type="jsonparse" path="price"]

        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]

        kraken_shib_eth_divide    [type="divide" input="$(kraken_shib_usd_parse)" divisor="$(kraken_eth_usd_parse)"]
        kraken_shib_eth_divide_multiply [type="multiply" times=1000000000000000000]

        okx_shib_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/SHIB/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_shib_usd_parse    [type="jsonparse" path="price"]

        okx_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_eth_usd_parse    [type="jsonparse" path="price"]

        okx_shib_eth_divide    [type="divide" input="$(okx_shib_usd_parse)" divisor="$(okx_eth_usd_parse)"]
        okx_shib_eth_divide_multiply [type="multiply" times=1000000000000000000]

        median [type=median];

    binance_shib_usdt -> binance_shib_usdt_parse -> binance_shib_eth_divide
    binance_eth_usdt -> binance_eth_usdt_parse -> binance_shib_eth_divide
    binance_shib_eth_divide -> binance_shib_eth_divide_multiply
    coinbase_shib_usd -> coinbase_shib_usd_parse -> coinbase_shib_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_shib_eth_divide
    coinbase_shib_eth_divide -> coinbase_shib_eth_divide_multiply
    coingecko_shib_usd -> coingecko_shib_usd_parse -> coingecko_shib_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_shib_eth_divide
    coingecko_shib_eth_divide -> coingecko_shib_eth_divide_multiply
    cryptocompare_shib_usd -> cryptocompare_shib_usd_parse -> cryptocompare_shib_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_shib_eth_divide
    cryptocompare_shib_eth_divide -> cryptocompare_shib_eth_divide_multiply
    kraken_shib_usd -> kraken_shib_usd_parse -> kraken_shib_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_shib_eth_divide
    kraken_shib_eth_divide -> kraken_shib_eth_divide_multiply
    okx_shib_usd -> okx_shib_usd_parse -> okx_shib_eth_divide
    okx_eth_usd -> okx_eth_usd_parse -> okx_shib_eth_divide
    okx_shib_eth_divide -> okx_shib_eth_divide_multiply
    binance_shib_eth_divide_multiply -> median;
    coinbase_shib_eth_divide_multiply -> median;
    coingecko_shib_eth_divide_multiply -> median;
    cryptocompare_shib_eth_divide_multiply -> median;
    kraken_shib_eth_divide_multiply -> median;
    okx_shib_eth_divide_multiply -> median;
"""
