type = "offchainreporting"
schemaVersion = 1
name = "SNX / ETH"
externalJobID = "e894ca84-c610-5029-9b4d-e9e1c5096af1"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        binance_snx_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/SNX/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_snx_usdt_parse    [type="jsonparse" path="price"]

        binance_eth_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/ETH/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_eth_usdt_parse    [type="jsonparse" path="price"]

        binance_snx_eth_divide    [type="divide" input="$(binance_snx_usdt_parse)" divisor="$(binance_eth_usdt_parse)"]
        binance_snx_eth_divide_multiply [type="multiply" times=1000000000000000000]

        coinbase_snx_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/SNX/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_snx_usd_parse    [type="jsonparse" path="price"]

        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]

        coinbase_snx_eth_divide    [type="divide" input="$(coinbase_snx_usd_parse)" divisor="$(coinbase_eth_usd_parse)"]
        coinbase_snx_eth_divide_multiply [type="multiply" times=1000000000000000000]

        coingecko_snx_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/havven/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_snx_usd_parse    [type="jsonparse" path="price"]

        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/ethereum/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]

        coingecko_snx_eth_divide    [type="divide" input="$(coingecko_snx_usd_parse)" divisor="$(coingecko_eth_usd_parse)"]
        coingecko_snx_eth_divide_multiply [type="multiply" times=1000000000000000000]

        cryptocompare_snx_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/SNX/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_snx_usd_parse    [type="jsonparse" path="price"]

        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]

        cryptocompare_snx_eth_divide    [type="divide" input="$(cryptocompare_snx_usd_parse)" divisor="$(cryptocompare_eth_usd_parse)"]
        cryptocompare_snx_eth_divide_multiply [type="multiply" times=1000000000000000000]

        kraken_snx_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/SNX/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_snx_usd_parse    [type="jsonparse" path="price"]

        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]

        kraken_snx_eth_divide    [type="divide" input="$(kraken_snx_usd_parse)" divisor="$(kraken_eth_usd_parse)"]
        kraken_snx_eth_divide_multiply [type="multiply" times=1000000000000000000]

        okx_snx_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/SNX/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_snx_usd_parse    [type="jsonparse" path="price"]

        okx_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_eth_usd_parse    [type="jsonparse" path="price"]

        okx_snx_eth_divide    [type="divide" input="$(okx_snx_usd_parse)" divisor="$(okx_eth_usd_parse)"]
        okx_snx_eth_divide_multiply [type="multiply" times=1000000000000000000]

        median [type=median];

    binance_snx_usdt -> binance_snx_usdt_parse -> binance_snx_eth_divide
    binance_eth_usdt -> binance_eth_usdt_parse -> binance_snx_eth_divide
    binance_snx_eth_divide -> binance_snx_eth_divide_multiply
    coinbase_snx_usd -> coinbase_snx_usd_parse -> coinbase_snx_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_snx_eth_divide
    coinbase_snx_eth_divide -> coinbase_snx_eth_divide_multiply
    coingecko_snx_usd -> coingecko_snx_usd_parse -> coingecko_snx_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_snx_eth_divide
    coingecko_snx_eth_divide -> coingecko_snx_eth_divide_multiply
    cryptocompare_snx_usd -> cryptocompare_snx_usd_parse -> cryptocompare_snx_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_snx_eth_divide
    cryptocompare_snx_eth_divide -> cryptocompare_snx_eth_divide_multiply
    kraken_snx_usd -> kraken_snx_usd_parse -> kraken_snx_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_snx_eth_divide
    kraken_snx_eth_divide -> kraken_snx_eth_divide_multiply
    okx_snx_usd -> okx_snx_usd_parse -> okx_snx_eth_divide
    okx_eth_usd -> okx_eth_usd_parse -> okx_snx_eth_divide
    okx_snx_eth_divide -> okx_snx_eth_divide_multiply
    binance_snx_eth_divide_multiply -> median;
    coinbase_snx_eth_divide_multiply -> median;
    coingecko_snx_eth_divide_multiply -> median;
    cryptocompare_snx_eth_divide_multiply -> median;
    kraken_snx_eth_divide_multiply -> median;
    okx_snx_eth_divide_multiply -> median;
"""
