type = "offchainreporting"
schemaVersion = 1
name = "OCR Oracle: STETH / USD Price Feed"
externalJobID = "48eadfe3-f071-5cf1-8a56-9fce16fd99d9"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "0x440AD62ecF8745267387Ec84b9fa55bAE58e3B88"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://min-api.cryptocompare.com/data/price?fsym=STETH&tsyms=USD"];
    ds1_parse [type=jsonparse path="USD"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=staked-ether&vs_currencies=usd"];
    ds2_parse [type=jsonparse path="staked-ether,usd"];
    ds2_multiply [type=multiply times=100000000];
    ds3 [type=http method=GET url="https://www.okx.com/api/v5/market/ticker?instId=STETH-USD"];
    ds3_parse [type=jsonparse path="data,0,last"];
    ds3_multiply [type=multiply times=100000000];
    median [type=median];
    
    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds3 -> ds3_parse -> ds3_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
    ds3_multiply -> median;
"""
