type = "offchainreporting"
schemaVersion = 1
name = "STETH / ETH"
externalJobID = "f122e41d-0811-5165-94cd-9adcfba69626"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        coingecko_steth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/ethereum/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_steth_usd_parse    [type="jsonparse" path="price"]

        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/staked-ether/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]

        coingecko_steth_eth_divide    [type="divide" input="$(coingecko_steth_usd_parse)" divisor="$(coingecko_eth_usd_parse)"]
        coingecko_steth_eth_divide_multiply [type="multiply" times=1000000000000000000]

        median [type=median];

    coingecko_steth_usd -> coingecko_steth_usd_parse -> coingecko_steth_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_steth_eth_divide
    coingecko_steth_eth_divide -> coingecko_steth_eth_divide_multiply
    coingecko_steth_eth_divide_multiply -> median;
"""
