type = "offchainreporting"
schemaVersion = 1
name = "SWELL / ETH"
externalJobID = "aed53e8d-5fdd-5313-a750-e25b94dc9d3e"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        coinbase_swell_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/SWELL/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_swell_usd_parse    [type="jsonparse" path="price"]
    
        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]
    
        coinbase_swell_eth_divide    [type="divide" input="$(coinbase_swell_usd_parse)" divisor="$(coinbase_eth_usd_parse)"]
        coinbase_swell_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_swell_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/layerzero-bridged-swell/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_swell_usd_parse    [type="jsonparse" path="price"]
    
        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/bifrost-bridged-eth-bifrost/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]
    
        coingecko_swell_eth_divide    [type="divide" input="$(coingecko_swell_usd_parse)" divisor="$(coingecko_eth_usd_parse)"]
        coingecko_swell_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_swell_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/SWELL/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_swell_usd_parse    [type="jsonparse" path="price"]
    
        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]
    
        cryptocompare_swell_eth_divide    [type="divide" input="$(cryptocompare_swell_usd_parse)" divisor="$(cryptocompare_eth_usd_parse)"]
        cryptocompare_swell_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        kraken_swell_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/SWELL/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_swell_usd_parse    [type="jsonparse" path="price"]
    
        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]
    
        kraken_swell_eth_divide    [type="divide" input="$(kraken_swell_usd_parse)" divisor="$(kraken_eth_usd_parse)"]
        kraken_swell_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        median [type=median];
    
    coinbase_swell_usd -> coinbase_swell_usd_parse -> coinbase_swell_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_swell_eth_divide
    coinbase_swell_eth_divide -> coinbase_swell_eth_divide_multiply
    coingecko_swell_usd -> coingecko_swell_usd_parse -> coingecko_swell_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_swell_eth_divide
    coingecko_swell_eth_divide -> coingecko_swell_eth_divide_multiply
    cryptocompare_swell_usd -> cryptocompare_swell_usd_parse -> cryptocompare_swell_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_swell_eth_divide
    cryptocompare_swell_eth_divide -> cryptocompare_swell_eth_divide_multiply
    kraken_swell_usd -> kraken_swell_usd_parse -> kraken_swell_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_swell_eth_divide
    kraken_swell_eth_divide -> kraken_swell_eth_divide_multiply
    coinbase_swell_eth_divide_multiply -> median;
    coingecko_swell_eth_divide_multiply -> median;
    cryptocompare_swell_eth_divide_multiply -> median;
    kraken_swell_eth_divide_multiply -> median;
"""
