type = "offchainreporting"
schemaVersion = 1
name = "TWT / BNB"
externalJobID = "f26a0cfb-a79b-53ee-828e-79864996eb12"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        coingecko_twt_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/trust-wallet-token/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_twt_usd_parse    [type="jsonparse" path="price"]
        coingecko_twt_usd_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_bnb_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/bifrost-bridged-bnb-bifrost/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_bnb_usd_parse    [type="jsonparse" path="price"]
        coingecko_bnb_usd_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_twt_bnb_divide    [type="divide" input="$(coingecko_twt_usd_multiply)" divisor="$(coingecko_bnb_usd_multiply)" times=1000000000000000000]
    
        cryptocompare_twt_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/TWT/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_twt_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_twt_usd_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_bnb_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/BNB/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_bnb_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_bnb_usd_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_twt_bnb_divide    [type="divide" input="$(cryptocompare_twt_usd_multiply)" divisor="$(cryptocompare_bnb_usd_multiply)" times=1000000000000000000]
    
        median [type=median];
    
    coingecko_twt_usd -> coingecko_twt_usd_parse -> coingecko_twt_usd_multiply -> coingecko_twt_bnb_divide
    coingecko_bnb_usd -> coingecko_bnb_usd_parse -> coingecko_bnb_usd_multiply -> coingecko_twt_bnb_divide
    cryptocompare_twt_usd -> cryptocompare_twt_usd_parse -> cryptocompare_twt_usd_multiply -> cryptocompare_twt_bnb_divide
    cryptocompare_bnb_usd -> cryptocompare_bnb_usd_parse -> cryptocompare_bnb_usd_multiply -> cryptocompare_twt_bnb_divide
    coingecko_twt_bnb_divide -> median;
    cryptocompare_twt_bnb_divide -> median;
"""
