type = "offchainreporting"
schemaVersion = 1
name = "UNI / ETH"
externalJobID = "1e9066c4-ddf2-56d2-b0b8-fb573615ef64"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        binance_uni_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/UNI/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_uni_usdt_parse    [type="jsonparse" path="price"]
        binance_uni_usdt_multiply [type="multiply" times=1000000000000000000]
    
        binance_eth_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/ETH/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_eth_usdt_parse    [type="jsonparse" path="price"]
        binance_eth_usdt_multiply [type="multiply" times=1000000000000000000]
    
        binance_uni_eth_divide    [type="divide" input="$(binance_uni_usdt_multiply)" divisor="$(binance_eth_usdt_multiply)" times=1000000000000000000]
    
        coinbase_uni_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/UNI/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_uni_usd_parse    [type="jsonparse" path="price"]
        coinbase_uni_usd_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]
        coinbase_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_uni_eth_divide    [type="divide" input="$(coinbase_uni_usd_multiply)" divisor="$(coinbase_eth_usd_multiply)" times=1000000000000000000]
    
        coingecko_uni_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/linea-bridged-uni-linea/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_uni_usd_parse    [type="jsonparse" path="price"]
        coingecko_uni_usd_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/bifrost-bridged-eth-bifrost/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]
        coingecko_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_uni_eth_divide    [type="divide" input="$(coingecko_uni_usd_multiply)" divisor="$(coingecko_eth_usd_multiply)" times=1000000000000000000]
    
        cryptocompare_uni_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/UNI/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_uni_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_uni_usd_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]
        cryptocompare_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_uni_eth_divide    [type="divide" input="$(cryptocompare_uni_usd_multiply)" divisor="$(cryptocompare_eth_usd_multiply)" times=1000000000000000000]
    
        kraken_uni_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/UNI/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_uni_usd_parse    [type="jsonparse" path="price"]
        kraken_uni_usd_multiply [type="multiply" times=1000000000000000000]
    
        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]
        kraken_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        kraken_uni_eth_divide    [type="divide" input="$(kraken_uni_usd_multiply)" divisor="$(kraken_eth_usd_multiply)" times=1000000000000000000]
    
        okx_uni_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/UNI/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_uni_usd_parse    [type="jsonparse" path="price"]
        okx_uni_usd_multiply [type="multiply" times=1000000000000000000]
    
        okx_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_eth_usd_parse    [type="jsonparse" path="price"]
        okx_eth_usd_multiply [type="multiply" times=1000000000000000000]
    
        okx_uni_eth_divide    [type="divide" input="$(okx_uni_usd_multiply)" divisor="$(okx_eth_usd_multiply)" times=1000000000000000000]
    
        median [type=median];
    
    binance_uni_usdt -> binance_uni_usdt_parse -> binance_uni_usdt_multiply -> binance_uni_eth_divide
    binance_eth_usdt -> binance_eth_usdt_parse -> binance_eth_usdt_multiply -> binance_uni_eth_divide
    coinbase_uni_usd -> coinbase_uni_usd_parse -> coinbase_uni_usd_multiply -> coinbase_uni_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_eth_usd_multiply -> coinbase_uni_eth_divide
    coingecko_uni_usd -> coingecko_uni_usd_parse -> coingecko_uni_usd_multiply -> coingecko_uni_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_eth_usd_multiply -> coingecko_uni_eth_divide
    cryptocompare_uni_usd -> cryptocompare_uni_usd_parse -> cryptocompare_uni_usd_multiply -> cryptocompare_uni_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_eth_usd_multiply -> cryptocompare_uni_eth_divide
    kraken_uni_usd -> kraken_uni_usd_parse -> kraken_uni_usd_multiply -> kraken_uni_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_eth_usd_multiply -> kraken_uni_eth_divide
    okx_uni_usd -> okx_uni_usd_parse -> okx_uni_usd_multiply -> okx_uni_eth_divide
    okx_eth_usd -> okx_eth_usd_parse -> okx_eth_usd_multiply -> okx_uni_eth_divide
    binance_uni_eth_divide -> median;
    coinbase_uni_eth_divide -> median;
    coingecko_uni_eth_divide -> median;
    cryptocompare_uni_eth_divide -> median;
    kraken_uni_eth_divide -> median;
    okx_uni_eth_divide -> median;
"""
