type = "offchainreporting"
schemaVersion = 1
name = "WBTC / ETH"
externalJobID = "0070dfe2-4190-573d-b5be-839af9866fe1"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        coinbase_wbtc_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/WBTC/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_wbtc_usd_parse    [type="jsonparse" path="price"]
    
        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]
    
        coinbase_wbtc_eth_divide    [type="divide" input="$(coinbase_wbtc_usd_parse)" divisor="$(coinbase_eth_usd_parse)"]
        coinbase_wbtc_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_wbtc_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/arbitrum-bridged-wbtc-arbitrum-one/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_wbtc_usd_parse    [type="jsonparse" path="price"]
    
        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/bifrost-bridged-eth-bifrost/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]
    
        coingecko_wbtc_eth_divide    [type="divide" input="$(coingecko_wbtc_usd_parse)" divisor="$(coingecko_eth_usd_parse)"]
        coingecko_wbtc_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_wbtc_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/WBTC/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_wbtc_usd_parse    [type="jsonparse" path="price"]
    
        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]
    
        cryptocompare_wbtc_eth_divide    [type="divide" input="$(cryptocompare_wbtc_usd_parse)" divisor="$(cryptocompare_eth_usd_parse)"]
        cryptocompare_wbtc_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        kraken_wbtc_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/WBTC/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_wbtc_usd_parse    [type="jsonparse" path="price"]
    
        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]
    
        kraken_wbtc_eth_divide    [type="divide" input="$(kraken_wbtc_usd_parse)" divisor="$(kraken_eth_usd_parse)"]
        kraken_wbtc_eth_divide_multiply [type="multiply" times=1000000000000000000]
    
        median [type=median];
    
    coinbase_wbtc_usd -> coinbase_wbtc_usd_parse -> coinbase_wbtc_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_wbtc_eth_divide
    coinbase_wbtc_eth_divide -> coinbase_wbtc_eth_divide_multiply
    coingecko_wbtc_usd -> coingecko_wbtc_usd_parse -> coingecko_wbtc_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_wbtc_eth_divide
    coingecko_wbtc_eth_divide -> coingecko_wbtc_eth_divide_multiply
    cryptocompare_wbtc_usd -> cryptocompare_wbtc_usd_parse -> cryptocompare_wbtc_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_wbtc_eth_divide
    cryptocompare_wbtc_eth_divide -> cryptocompare_wbtc_eth_divide_multiply
    kraken_wbtc_usd -> kraken_wbtc_usd_parse -> kraken_wbtc_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_wbtc_eth_divide
    kraken_wbtc_eth_divide -> kraken_wbtc_eth_divide_multiply
    coinbase_wbtc_eth_divide_multiply -> median;
    coingecko_wbtc_eth_divide_multiply -> median;
    cryptocompare_wbtc_eth_divide_multiply -> median;
    kraken_wbtc_eth_divide_multiply -> median;
"""
