type = "offchainreporting"
schemaVersion = 1
name = "OCR Oracle: WSTETH / USD Price Feed"
externalJobID = "5a268278-8117-5bdf-ae38-be1003da1c1e"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "0x09DAfc6d1cEE5E48d65e0b9e6061fa436bf0c5C1"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=arbitrum-bridged-wsteth-arbitrum&vs_currencies=usd"];
    ds1_parse [type=jsonparse path="arbitrum-bridged-wsteth-arbitrum,usd"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="https://api.coinbase.com/v2/prices/WSTETH-USD/spot"];
    ds2_parse [type=jsonparse path="USD"];
    ds2_multiply [type=multiply times=100000000];
    median [type=median];
    
    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
"""
