type = "offchainreporting"
schemaVersion = 1
name = "OCR Oracle: WTI / USD Price Feed"
externalJobID = "b0f0c42d-f222-5946-b36a-d705aed62ece"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "0x3be462B69Dd35Ce3d591fa162374606E9d9BA711"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=wrapped-club-tigres-uanl-kayen&vs_currencies=usd"];
    ds1_parse [type=jsonparse path="wrapped-club-tigres-uanl-kayen,usd"];
    ds1_multiply [type=multiply times=100000000];
    median [type=median];
    
    ds1 -> ds1_parse -> ds1_multiply;
    ds1_multiply -> median;
"""
