type = "offchainreporting"
schemaVersion = 1
name = "OCR Oracle: XPT / USD Price Feed"
externalJobID = "bac832cf-7b3e-5cab-abfa-ac405946c99a"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "0x423dd8166a8a"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="https://min-api.cryptocompare.com/data/price?fsym=XPT&tsyms=USD"];
    ds1_parse [type=jsonparse path="USD"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="https://api.coinbase.com/v2/prices/XPT-USD/spot"];
    ds2_parse [type=jsonparse path="USD"];
    ds2_multiply [type=multiply times=100000000];
    median [type=median];
    
    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
"""
