type = "offchainreporting"
schemaVersion = 1
name = "XRP / BNB"
externalJobID = "952eb4a7-b630-58f0-a97c-ff0db32b2d25"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        binance_xrp_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/XRP/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_xrp_usdt_parse    [type="jsonparse" path="price"]
    
        binance_bnb_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/BNB/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_bnb_usdt_parse    [type="jsonparse" path="price"]
    
        binance_xrp_bnb_divide    [type="divide" input="$(binance_xrp_usdt_parse)" divisor="$(binance_bnb_usdt_parse)"]
        binance_xrp_bnb_divide_multiply [type="multiply" times=1000000000000000000]
    
        coinbase_xrp_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/XRP/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_xrp_usd_parse    [type="jsonparse" path="price"]
    
        coinbase_bnb_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/BNB/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_bnb_usd_parse    [type="jsonparse" path="price"]
    
        coinbase_xrp_bnb_divide    [type="divide" input="$(coinbase_xrp_usd_parse)" divisor="$(coinbase_bnb_usd_parse)"]
        coinbase_xrp_bnb_divide_multiply [type="multiply" times=1000000000000000000]
    
        coingecko_xrp_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/binance-peg-xrp/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_xrp_usd_parse    [type="jsonparse" path="price"]
    
        coingecko_bnb_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/bifrost-bridged-bnb-bifrost/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_bnb_usd_parse    [type="jsonparse" path="price"]
    
        coingecko_xrp_bnb_divide    [type="divide" input="$(coingecko_xrp_usd_parse)" divisor="$(coingecko_bnb_usd_parse)"]
        coingecko_xrp_bnb_divide_multiply [type="multiply" times=1000000000000000000]
    
        cryptocompare_xrp_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/XRP/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_xrp_usd_parse    [type="jsonparse" path="price"]
    
        cryptocompare_bnb_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/BNB/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_bnb_usd_parse    [type="jsonparse" path="price"]
    
        cryptocompare_xrp_bnb_divide    [type="divide" input="$(cryptocompare_xrp_usd_parse)" divisor="$(cryptocompare_bnb_usd_parse)"]
        cryptocompare_xrp_bnb_divide_multiply [type="multiply" times=1000000000000000000]
    
        kraken_xrp_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/XRP/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_xrp_usd_parse    [type="jsonparse" path="price"]
    
        kraken_bnb_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/BNB/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_bnb_usd_parse    [type="jsonparse" path="price"]
    
        kraken_xrp_bnb_divide    [type="divide" input="$(kraken_xrp_usd_parse)" divisor="$(kraken_bnb_usd_parse)"]
        kraken_xrp_bnb_divide_multiply [type="multiply" times=1000000000000000000]
    
        okx_xrp_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/XRP/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_xrp_usd_parse    [type="jsonparse" path="price"]
    
        okx_bnb_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/BNB/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_bnb_usd_parse    [type="jsonparse" path="price"]
    
        okx_xrp_bnb_divide    [type="divide" input="$(okx_xrp_usd_parse)" divisor="$(okx_bnb_usd_parse)"]
        okx_xrp_bnb_divide_multiply [type="multiply" times=1000000000000000000]
    
        median [type=median];
    
    binance_xrp_usdt -> binance_xrp_usdt_parse -> binance_xrp_bnb_divide
    binance_bnb_usdt -> binance_bnb_usdt_parse -> binance_xrp_bnb_divide
    binance_xrp_bnb_divide -> binance_xrp_bnb_divide_multiply
    coinbase_xrp_usd -> coinbase_xrp_usd_parse -> coinbase_xrp_bnb_divide
    coinbase_bnb_usd -> coinbase_bnb_usd_parse -> coinbase_xrp_bnb_divide
    coinbase_xrp_bnb_divide -> coinbase_xrp_bnb_divide_multiply
    coingecko_xrp_usd -> coingecko_xrp_usd_parse -> coingecko_xrp_bnb_divide
    coingecko_bnb_usd -> coingecko_bnb_usd_parse -> coingecko_xrp_bnb_divide
    coingecko_xrp_bnb_divide -> coingecko_xrp_bnb_divide_multiply
    cryptocompare_xrp_usd -> cryptocompare_xrp_usd_parse -> cryptocompare_xrp_bnb_divide
    cryptocompare_bnb_usd -> cryptocompare_bnb_usd_parse -> cryptocompare_xrp_bnb_divide
    cryptocompare_xrp_bnb_divide -> cryptocompare_xrp_bnb_divide_multiply
    kraken_xrp_usd -> kraken_xrp_usd_parse -> kraken_xrp_bnb_divide
    kraken_bnb_usd -> kraken_bnb_usd_parse -> kraken_xrp_bnb_divide
    kraken_xrp_bnb_divide -> kraken_xrp_bnb_divide_multiply
    okx_xrp_usd -> okx_xrp_usd_parse -> okx_xrp_bnb_divide
    okx_bnb_usd -> okx_bnb_usd_parse -> okx_xrp_bnb_divide
    okx_xrp_bnb_divide -> okx_xrp_bnb_divide_multiply
    binance_xrp_bnb_divide_multiply -> median;
    coinbase_xrp_bnb_divide_multiply -> median;
    coingecko_xrp_bnb_divide_multiply -> median;
    cryptocompare_xrp_bnb_divide_multiply -> median;
    kraken_xrp_bnb_divide_multiply -> median;
    okx_xrp_bnb_divide_multiply -> median;
"""
