type = "offchainreporting"
schemaVersion = 1
name = "OCR Oracle: XTZ / USD Price Feed"
externalJobID = "a54196cd-bdc1-50a6-8776-589fd27d29dd"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "0x51F35B52398db28Bd74940Ca7b5c20e3f8C53dE1"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
    ds1 [type=http method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/XTZ/USDT"];
    ds1_parse [type=jsonparse path="price"];
    ds1_multiply [type=multiply times=100000000];
    ds2 [type=http method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/XTZ/USD"];
    ds2_parse [type=jsonparse path="price"];
    ds2_multiply [type=multiply times=100000000];
    ds3 [type=http method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/XTZ/USD"];
    ds3_parse [type=jsonparse path="price"];
    ds3_multiply [type=multiply times=100000000];
    ds4 [type=http method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/XTZ/USD"];
    ds4_parse [type=jsonparse path="price"];
    ds4_multiply [type=multiply times=100000000];
    ds5 [type=http method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/XTZ/USD"];
    ds5_parse [type=jsonparse path="price"];
    ds5_multiply [type=multiply times=100000000];
    ds6 [type=http method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/XTZ/USDT"];
    ds6_parse [type=jsonparse path="price"];
    ds6_multiply [type=multiply times=100000000];
    median [type=median];
    
    ds1 -> ds1_parse -> ds1_multiply;
    ds2 -> ds2_parse -> ds2_multiply;
    ds3 -> ds3_parse -> ds3_multiply;
    ds4 -> ds4_parse -> ds4_multiply;
    ds5 -> ds5_parse -> ds5_multiply;
    ds6 -> ds6_parse -> ds6_multiply;
    ds1_multiply -> median;
    ds2_multiply -> median;
    ds3_multiply -> median;
    ds4_multiply -> median;
    ds5_multiply -> median;
    ds6_multiply -> median;
"""
