type = "offchainreporting"
schemaVersion = 1
name = "XVS / BNB"
externalJobID = "d21a76b0-e1ea-58cc-89da-fadf7a30720c"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        coingecko_xvs_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/venus/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_xvs_usd_parse    [type="jsonparse" path="price"]

        coingecko_bnb_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/binancecoin/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_bnb_usd_parse    [type="jsonparse" path="price"]

        coingecko_xvs_bnb_divide    [type="divide" input="$(coingecko_xvs_usd_parse)" divisor="$(coingecko_bnb_usd_parse)"]
        coingecko_xvs_bnb_divide_multiply [type="multiply" times=1000000000000000000]

        cryptocompare_xvs_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/XVS/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_xvs_usd_parse    [type="jsonparse" path="price"]

        cryptocompare_bnb_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/BNB/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_bnb_usd_parse    [type="jsonparse" path="price"]

        cryptocompare_xvs_bnb_divide    [type="divide" input="$(cryptocompare_xvs_usd_parse)" divisor="$(cryptocompare_bnb_usd_parse)"]
        cryptocompare_xvs_bnb_divide_multiply [type="multiply" times=1000000000000000000]

        median [type=median];

    coingecko_xvs_usd -> coingecko_xvs_usd_parse -> coingecko_xvs_bnb_divide
    coingecko_bnb_usd -> coingecko_bnb_usd_parse -> coingecko_xvs_bnb_divide
    coingecko_xvs_bnb_divide -> coingecko_xvs_bnb_divide_multiply
    cryptocompare_xvs_usd -> cryptocompare_xvs_usd_parse -> cryptocompare_xvs_bnb_divide
    cryptocompare_bnb_usd -> cryptocompare_bnb_usd_parse -> cryptocompare_xvs_bnb_divide
    cryptocompare_xvs_bnb_divide -> cryptocompare_xvs_bnb_divide_multiply
    coingecko_xvs_bnb_divide_multiply -> median;
    cryptocompare_xvs_bnb_divide_multiply -> median;
"""
