type = "offchainreporting"
schemaVersion = 1
name = "YFI / ETH"
externalJobID = "bececf7c-0f7f-5c96-ac1e-023b777166c0"
forwardingAllowed = false
maxTaskDuration = "0s"
blockchainTimeout = "20s"
contractAddress = "$JOB_CA"
contractConfigConfirmations = 3
contractConfigTrackerPollInterval = "1m0s"
evmChainID = "$EVM_CHAIN_ID"
isBootstrapPeer = $IS_BOOTSTRAP
p2pPeerID = "$P2P_PEER_ID"
p2pBootstrapPeers = $P2P_BOOTSTRAP_PEERS
# p2pv2Bootstrappers = $P2P_BOOTSTRAP_PEERS
keyBundleID = "$OCR_KEY_BUNDLE_ID"
observationTimeout = "10s"
transmitterAddress = "$TRANSMITTER_ADDRESS"
observationSource = """
        binance_yfi_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/YFI/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_yfi_usdt_parse    [type="jsonparse" path="price"]

        binance_eth_usdt          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/binance/ETH/USDT" allowUnrestrictedNetworkAccess=true retries=3]
        binance_eth_usdt_parse    [type="jsonparse" path="price"]

        binance_yfi_eth_divide    [type="divide" input="$(binance_yfi_usdt_parse)" divisor="$(binance_eth_usdt_parse)"]
        binance_yfi_eth_divide_multiply [type="multiply" times=1000000000000000000]

        coinbase_yfi_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/YFI/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_yfi_usd_parse    [type="jsonparse" path="price"]

        coinbase_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coinbase/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coinbase_eth_usd_parse    [type="jsonparse" path="price"]

        coinbase_yfi_eth_divide    [type="divide" input="$(coinbase_yfi_usd_parse)" divisor="$(coinbase_eth_usd_parse)"]
        coinbase_yfi_eth_divide_multiply [type="multiply" times=1000000000000000000]

        coingecko_yfi_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/yearn-finance/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_yfi_usd_parse    [type="jsonparse" path="price"]

        coingecko_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/coingecko/ethereum/USD" allowUnrestrictedNetworkAccess=true retries=3]
        coingecko_eth_usd_parse    [type="jsonparse" path="price"]

        coingecko_yfi_eth_divide    [type="divide" input="$(coingecko_yfi_usd_parse)" divisor="$(coingecko_eth_usd_parse)"]
        coingecko_yfi_eth_divide_multiply [type="multiply" times=1000000000000000000]

        cryptocompare_yfi_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/YFI/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_yfi_usd_parse    [type="jsonparse" path="price"]

        cryptocompare_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/cryptocompare/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        cryptocompare_eth_usd_parse    [type="jsonparse" path="price"]

        cryptocompare_yfi_eth_divide    [type="divide" input="$(cryptocompare_yfi_usd_parse)" divisor="$(cryptocompare_eth_usd_parse)"]
        cryptocompare_yfi_eth_divide_multiply [type="multiply" times=1000000000000000000]

        kraken_yfi_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/YFI/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_yfi_usd_parse    [type="jsonparse" path="price"]

        kraken_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/kraken/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        kraken_eth_usd_parse    [type="jsonparse" path="price"]

        kraken_yfi_eth_divide    [type="divide" input="$(kraken_yfi_usd_parse)" divisor="$(kraken_eth_usd_parse)"]
        kraken_yfi_eth_divide_multiply [type="multiply" times=1000000000000000000]

        okx_yfi_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/YFI/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_yfi_usd_parse    [type="jsonparse" path="price"]

        okx_eth_usd          [type="http" method=GET url="http://127.0.0.1:$PRICE_AGGREGATOR_PORT/quote/okx/ETH/USD" allowUnrestrictedNetworkAccess=true retries=3]
        okx_eth_usd_parse    [type="jsonparse" path="price"]

        okx_yfi_eth_divide    [type="divide" input="$(okx_yfi_usd_parse)" divisor="$(okx_eth_usd_parse)"]
        okx_yfi_eth_divide_multiply [type="multiply" times=1000000000000000000]

        median [type=median];

    binance_yfi_usdt -> binance_yfi_usdt_parse -> binance_yfi_eth_divide
    binance_eth_usdt -> binance_eth_usdt_parse -> binance_yfi_eth_divide
    binance_yfi_eth_divide -> binance_yfi_eth_divide_multiply
    coinbase_yfi_usd -> coinbase_yfi_usd_parse -> coinbase_yfi_eth_divide
    coinbase_eth_usd -> coinbase_eth_usd_parse -> coinbase_yfi_eth_divide
    coinbase_yfi_eth_divide -> coinbase_yfi_eth_divide_multiply
    coingecko_yfi_usd -> coingecko_yfi_usd_parse -> coingecko_yfi_eth_divide
    coingecko_eth_usd -> coingecko_eth_usd_parse -> coingecko_yfi_eth_divide
    coingecko_yfi_eth_divide -> coingecko_yfi_eth_divide_multiply
    cryptocompare_yfi_usd -> cryptocompare_yfi_usd_parse -> cryptocompare_yfi_eth_divide
    cryptocompare_eth_usd -> cryptocompare_eth_usd_parse -> cryptocompare_yfi_eth_divide
    cryptocompare_yfi_eth_divide -> cryptocompare_yfi_eth_divide_multiply
    kraken_yfi_usd -> kraken_yfi_usd_parse -> kraken_yfi_eth_divide
    kraken_eth_usd -> kraken_eth_usd_parse -> kraken_yfi_eth_divide
    kraken_yfi_eth_divide -> kraken_yfi_eth_divide_multiply
    okx_yfi_usd -> okx_yfi_usd_parse -> okx_yfi_eth_divide
    okx_eth_usd -> okx_eth_usd_parse -> okx_yfi_eth_divide
    okx_yfi_eth_divide -> okx_yfi_eth_divide_multiply
    binance_yfi_eth_divide_multiply -> median;
    coinbase_yfi_eth_divide_multiply -> median;
    coingecko_yfi_eth_divide_multiply -> median;
    cryptocompare_yfi_eth_divide_multiply -> median;
    kraken_yfi_eth_divide_multiply -> median;
    okx_yfi_eth_divide_multiply -> median;
"""
